all:
	@echo "Running convolution experiments"
	python src/convolution.py
	@echo "Running convolution experiments-openCV"
	python dbg/convOpenCV.py
	@echo "Running gaussian pyramid experiments"
#	python src/gaussian_pyramid.py
	@echo "Running laplacian pyramid experiments"
#	python src/laplacian_pyramid.py
	@echo "Running blending experiments"
#	python src/blending.py
	@echo "Running fourier transform experiments"
#	python src/fourier.py
	
clean:
	rm -rf output/*
	rm -f *.zip
