all:
	@echo "Running question 2 ..."
	python3 src/p0-2.py
	@echo "Running question 3 ..."
	python3 src/p0-3.py
	@echo "Running question 4 ..."
	python3 src/p0-4.py
	@echo "Running question 5 ..."
	python3 src/p0-5.py

clean:
	rm -rf output/*
	rm -f *.zip
